function ttf = tt_fun(fun, relAcc, d)
%TT_FUN Construct TT approximation to function using TT-SVD
%
%   tt_fun(fun, relAcc, d) computes the TT approximation of the vector
%   generated by evauating function handle fun at 2^d uniformly spaced
%   discretization points in [0, 1]:
%
%       >> x = linspace(0, 1, 2^d + 1); x = x(1 : end - 1); x = x';
%       >> h = x(2) - x(1);
%       >> x = x + 0.5 * h;     % center points
%       >> f = fun(x); 
%
%   The TT decomposition is then obtained by running TT-SVD with relative
%   accuracy relAcc on the tensorized function value vector.

N = 2^d;
x = linspace(0, 1, N + 1)'; x = x(1 : N);
h = x(2) - x(1);
x = 0.5 * h + x;
f = fun(x);

F = reshape(f, 2 * ones(1, d));
ttf = tt_tensor(F, relAcc);

relErr = norm(full(ttf) - f) / norm(f);
fprintf('relative error in compression is %.e\n', relErr);

end